{"name": "test_01_login_error[data2]", "status": "passed", "attachments": [{"name": "log", "source": "a69a2c55-b6f5-4331-a07c-21f579570e2e-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'Caseid': 3, 'module': '登录', 'title': '输入不符规则的用户名', 'username': '123654', 'password': '222', 'expect': '请输入正确的手机号'}"}], "start": 1558759847195, "stop": 1558759847805, "uuid": "a402a10c-1f28-42f9-9b76-85d48f947dd0", "historyId": "823adf4c3db60aa5e397d42c2f4291a7", "fullName": "Cases.test_login#test_01_login_error[data2]", "labels": [{"name": "tag", "value": "error"}, {"name": "parentSuite", "value": "Cases"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "LAPTOP-VNEUB3U3"}, {"name": "thread", "value": "14360-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Cases.test_login"}]}