<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>接口测试</title>
    <meta name="generator" content="HTMLTestRunner 0.8.2.2"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
    <script src="http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    
<style type="text/css" media="screen">
body        { font-family: Microsoft YaHei,Tahoma,arial,helvetica,sans-serif;padding: 20px; font-size: 120%; }
table       { font-size: 100%; }
/* -- heading ---------------------------------------------------------------------- */
.heading {
    margin-top: 0ex;
    margin-bottom: 1ex;
}
.heading .description {
    margin-top: 4ex;
    margin-bottom: 6ex;
}
/* -- report ------------------------------------------------------------------------ */
#total_row  { font-weight: bold; }
.passCase   { color: #5cb85c; }
.failCase   { color: #d9534f; font-weight: bold; }
.errorCase  { color: #f0ad4e; font-weight: bold; }
.hiddenRow  { display: none; }
.testcase   { margin-left: 2em; }
</style>

</head>
<body >
<script language="javascript" type="text/javascript">
output_list = Array();
/*level 调整增加只显示通过用例的分类 --Findyou
0:Summary //all hiddenRow
1:Failed  //pt hiddenRow, ft none
2:Pass    //pt none, ft hiddenRow
3:All     //pt none, ft none
*/
function showCase(level) {
    trs = document.getElementsByTagName("tr");
    for (var i = 0; i < trs.length; i++) {
        tr = trs[i];
        id = tr.id;
        if (id.substr(0,2) == 'ft') {
            if (level == 2 || level == 0 ) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
        if (id.substr(0,2) == 'pt') {
            if (level < 2) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
    }
    //加入【详细】切换文字变化 --Findyou
    detail_class=document.getElementsByClassName('detail');
	//console.log(detail_class.length)
	if (level == 3) {
		for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="收起"
		}
	}
	else{
			for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="详细"
		}
	}
}
function showClassDetail(cid, count) {
    var id_list = Array(count);
    var toHide = 1;
    for (var i = 0; i < count; i++) {
        //ID修改 点 为 下划线 -Findyou
        tid0 = 't' + cid.substr(1) + '_' + (i+1);
        tid = 'f' + tid0;
        tr = document.getElementById(tid);
        if (!tr) {
            tid = 'p' + tid0;
            tr = document.getElementById(tid);
        }
        id_list[i] = tid;
        if (tr.className) {
            toHide = 0;
        }
    }
    for (var i = 0; i < count; i++) {
        tid = id_list[i];
        //修改点击无法收起的BUG，加入【详细】切换文字变化 --Findyou
        if (toHide) {
            document.getElementById(tid).className = 'hiddenRow';
            document.getElementById(cid).innerText = "详细"
        }
        else {
            document.getElementById(tid).className = '';
            document.getElementById(cid).innerText = "收起"
        }
    }
}
function html_escape(s) {
    s = s.replace(/&/g,'&amp;');
    s = s.replace(/</g,'&lt;');
    s = s.replace(/>/g,'&gt;');
    return s;
}
</script>
<div class='heading'>
<h1 style="font-family: Microsoft YaHei">接口测试</h1>
<p class='attribute'><strong>测试人员 : </strong> 小明</p>
<p class='attribute'><strong>开始时间 : </strong> 2019-04-28 21:13:08</p>
<p class='attribute'><strong>合计耗时 : </strong> 0:00:03.996341</p>
<p class='attribute'><strong>测试结果 : </strong> 共 18，通过 9，失败 4，错误 5，通过率= 50.00%</p>

<p class='description'>webservice接口测试</p>
</div>


<p id='show_detail_line'>
<a class="btn btn-primary" href='javascript:showCase(0)'>概要{ 50.00% }</a>
<a class="btn btn-danger" href='javascript:showCase(1)'>失败{ 4 }</a>
<a class="btn btn-success" href='javascript:showCase(2)'>通过{ 9 }</a>
<a class="btn btn-info" href='javascript:showCase(3)'>所有{ 18 }</a>
</p>
<table id='result_table' class="table table-condensed table-bordered table-hover">
<colgroup>
<col align='left' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
</colgroup>
<tr id='header_row' class="text-center success" style="font-weight: bold;font-size: 16px;">
    <td>用例集/测试用例</td>
    <td>总计</td>
    <td>通过</td>
    <td>失败</td>
    <td>错误</td>
    <td>详细</td>
</tr>

<tr class='errorClass warning'>
    <td>WebService.test_data.cases.sendcode.SendCode</td>
    <td class="text-center">9</td>
    <td class="text-center">4</td>
    <td class="text-center">0</td>
    <td class="text-center">5</td>
    <td class="text-center"><a href="javascript:showClassDetail('c1',9)" class="detail" id='c1'>详细</a></td>
</tr>

<tr id='pt1_1' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_sendCode_1__1___sendmsg_____url__sms_service_war_1_0_ws_smsFacade_ws_wsdl____发送验证码______client_ip___192_168_1_225___tmpl_id__1__mobile____mobile_________sql___select_count__mobile___from_sms_db__num__t_mvcode_info__nu__where_Fmobile_no__mobile___n_______retCode__0__retInfo___ok______Method_not_found___SMSServiceImplService_SMSServiceImplPort_userRegister_____PASS__: list() -> new empty list</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt1_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt1_1'>通过</button>
    <div id='div_pt1_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt1_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt1_1'>通过</button>
    <div id='div_pt1_1' class="collapse in" align="left">
    <pre>
    
pt1_1: [2019-04-28 21:13:08,412]-[INFO]-[log_module.py-test_log]-[日志信息]:正在执行sendmsg模块1条用例，测试数据是{'client_ip':'192.168.1.225','tmpl_id':1,'mobile':'18296207778'}
[2019-04-28 21:13:08,976]-[INFO]-[log_module.py-test_log]-[日志信息]:实际结果是(result){
   retCode = "0"
   retInfo = "ok"
 }，测试结果是：FAILED


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_2' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_sendCode_2__2___sendmsg_____url__sms_service_war_1_0_ws_smsFacade_ws_wsdl____手机号码不足11位______client_ip___192_168_1_225___tmpl_id__1__mobile___1369654123_____None___Server_raised_fault___手机号码错误____None__None_: list() -> new empty list</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt1_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt1_2'>通过</button>
    <div id='div_pt1_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt1_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt1_2'>通过</button>
    <div id='div_pt1_2' class="collapse in" align="left">
    <pre>
    
pt1_2: [2019-04-28 21:13:08,977]-[INFO]-[log_module.py-test_log]-[日志信息]:正在执行sendmsg模块2条用例，测试数据是{'client_ip':'192.168.1.225','tmpl_id':1,'mobile':'1369654123'}
&lt;suds.sax.document.Document object at 0x0E07EB30&gt;
[2019-04-28 21:13:09,141]-[INFO]-[log_module.py-test_log]-[日志信息]:实际结果是Server raised fault: '手机号码错误'，测试结果是：PASS


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_3' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_sendCode_3__3___sendmsg_____url__sms_service_war_1_0_ws_smsFacade_ws_wsdl____手机号码大于11位______client_ip___192_168_1_225___tmpl_id__1__mobile___1369654123254_____None___Server_raised_fault___手机号码错误____None__None_: list() -> new empty list</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt1_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt1_3'>通过</button>
    <div id='div_pt1_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt1_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt1_3'>通过</button>
    <div id='div_pt1_3' class="collapse in" align="left">
    <pre>
    
pt1_3: [2019-04-28 21:13:09,142]-[INFO]-[log_module.py-test_log]-[日志信息]:正在执行sendmsg模块3条用例，测试数据是{'client_ip':'192.168.1.225','tmpl_id':1,'mobile':'1369654123254'}
&lt;suds.sax.document.Document object at 0x0E09BFB0&gt;
[2019-04-28 21:13:09,287]-[INFO]-[log_module.py-test_log]-[日志信息]:实际结果是Server raised fault: '手机号码错误'，测试结果是：PASS


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_4' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_sendCode_4__4___sendmsg_____url__sms_service_war_1_0_ws_smsFacade_ws_wsdl____不填手机号______client_ip___192_168_1_225___tmpl_id__1__mobile________None___Server_raised_fault___手机号码错误____None__None_: list() -> new empty list</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt1_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt1_4'>通过</button>
    <div id='div_pt1_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt1_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt1_4'>通过</button>
    <div id='div_pt1_4' class="collapse in" align="left">
    <pre>
    
pt1_4: [2019-04-28 21:13:09,287]-[INFO]-[log_module.py-test_log]-[日志信息]:正在执行sendmsg模块4条用例，测试数据是{'client_ip':'192.168.1.225','tmpl_id':1,'mobile':''}
&lt;suds.sax.document.Document object at 0x0E05F350&gt;
[2019-04-28 21:13:09,449]-[INFO]-[log_module.py-test_log]-[日志信息]:实际结果是Server raised fault: '手机号码错误'，测试结果是：PASS


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_5' class='none'>
    <td class='errorCase'><div class='testcase'>test_sendCode_5__5___register_____url__finance_user_info_war_1_0_ws_financeUserInfoFacade_ws_wsdl____正常注册______verify_code___fverifyCode___user_id____mobile____channel_id___1___pwd____pwd____mobile____mobile____ip___192_168_1_107________sq2___select_Fverify_code_from_sms_db__num__t_mvcode_info__nu__where_Fmobile_no__mobile____sq3___select_Fpwd_Fmobile_from_user_db_t_user_info_where_Fuser_id__mobile____sq4___select_count_Fuid__from_user_db_t_user_info_where_Fuser_id__mobile_________retCode__0__retInfo___ok______0____20042003____FAILED__: list() -> new empty list</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_5'>错误</button>
    <div id='div_ft1_5' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_5'>错误</button>
    <div id='div_ft1_5' class="collapse in" align="left">
    <pre>
    
ft1_5: Traceback (most recent call last):
  File "C:\python35\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\pycharm\WebService\test_data\cases\sendcode.py", line 23, in test_sendCode
    mn=Dopymysql().select_db(eval(SQL)['sql'])
KeyError: 'sql'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_6' class='none'>
    <td class='errorCase'><div class='testcase'>test_sendCode_6__6___register_____url__finance_user_info_war_1_0_ws_financeUserInfoFacade_ws_wsdl____错误验证码______verify_code___00000___user_id____mobile____channel_id___1___pwd____pwd____mobile____mobile____ip___192_168_1_107_____None_____retCode__0__retInfo___ok_____None__None_: list() -> new empty list</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_6' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_6'>错误</button>
    <div id='div_ft1_6' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_6' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_6'>错误</button>
    <div id='div_ft1_6' class="collapse in" align="left">
    <pre>
    
ft1_6: [2019-04-28 21:13:09,450]-[INFO]-[log_module.py-test_log]-[日志信息]:正在执行register模块6条用例，测试数据是{'verify_code':'00000','user_id':'18296207778','channel_id':'1','pwd':'123456','mobile':'18296207778','ip':'192.168.1.107'}
Traceback (most recent call last):
  File "C:\python35\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\pycharm\WebService\test_data\cases\sendcode.py", line 49, in test_sendCode
    DoExcel(project_path.excel_path).write_Excel('test',CaseId+1,8,str(res))
UnboundLocalError: local variable 'res' referenced before assignment


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_7' class='none'>
    <td class='errorCase'><div class='testcase'>test_sendCode_7__7___register_____url__finance_user_info_war_1_0_ws_financeUserInfoFacade_ws_wsdl____重复注册______verify_code___fverifyCode___user_id____mobile____channel_id___1___pwd____pwd____mobile____mobile____ip___192_168_1_107_____None_____retCode__0__retInfo___ok_______commResult___n___retCode____20042003__n___retInfo____该用户已存在__n______PASS__: list() -> new empty list</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_7' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_7'>错误</button>
    <div id='div_ft1_7' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_7' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_7'>错误</button>
    <div id='div_ft1_7' class="collapse in" align="left">
    <pre>
    
ft1_7: [2019-04-28 21:13:09,797]-[INFO]-[log_module.py-test_log]-[日志信息]:正在执行register模块7条用例，测试数据是{'verify_code':'fverifyCode','user_id':'18296207778','channel_id':'1','pwd':'123456','mobile':'18296207778','ip':'192.168.1.107'}
Traceback (most recent call last):
  File "C:\python35\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\pycharm\WebService\test_data\cases\sendcode.py", line 49, in test_sendCode
    DoExcel(project_path.excel_path).write_Excel('test',CaseId+1,8,str(res))
UnboundLocalError: local variable 'res' referenced before assignment


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_8' class='none'>
    <td class='errorCase'><div class='testcase'>test_sendCode_8__8___register_____url__finance_user_info_war_1_0_ws_financeUserInfoFacade_ws_wsdl____手机号大于11位______verify_code___fverifyCode___user_id____mobile____channel_id___1___pwd___123456___mobile___1358634952468___ip___192_168_1_107_____None_____retCode__0__retInfo___ok_______commResult___n___retCode____19001__n___retInfo____手机号错误__n______PASS__: list() -> new empty list</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_8' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_8'>错误</button>
    <div id='div_ft1_8' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_8' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_8'>错误</button>
    <div id='div_ft1_8' class="collapse in" align="left">
    <pre>
    
ft1_8: [2019-04-28 21:13:09,821]-[INFO]-[log_module.py-test_log]-[日志信息]:正在执行register模块8条用例，测试数据是{'verify_code':'fverifyCode','user_id':'18296207778','channel_id':'1','pwd':'123456','mobile':'1358634952468','ip':'192.168.1.107'}
Traceback (most recent call last):
  File "C:\python35\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\pycharm\WebService\test_data\cases\sendcode.py", line 49, in test_sendCode
    DoExcel(project_path.excel_path).write_Excel('test',CaseId+1,8,str(res))
UnboundLocalError: local variable 'res' referenced before assignment


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_9' class='none'>
    <td class='errorCase'><div class='testcase'>test_sendCode_9__9___register_____url__finance_user_info_war_1_0_ws_financeUserInfoFacade_ws_wsdl____失效验证码______verify_code___865562___user_id___18296208167___channel_id___1___pwd___123456___mobile___18296208167___ip___192_168_1_107_____None_____retCode__0__retInfo___ok_____None__None_: list() -> new empty list</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_9' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_9'>错误</button>
    <div id='div_ft1_9' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_9' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_9'>错误</button>
    <div id='div_ft1_9' class="collapse in" align="left">
    <pre>
    
ft1_9: [2019-04-28 21:13:09,841]-[INFO]-[log_module.py-test_log]-[日志信息]:正在执行register模块9条用例，测试数据是{'verify_code':'865562','user_id':'18296208167','channel_id':'1','pwd':'123456','mobile':'18296208167','ip':'192.168.1.107'}
Traceback (most recent call last):
  File "C:\python35\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\pycharm\WebService\test_data\cases\sendcode.py", line 49, in test_sendCode
    DoExcel(project_path.excel_path).write_Excel('test',CaseId+1,8,str(res))
UnboundLocalError: local variable 'res' referenced before assignment


    </pre>
    </div>
    </td>
</tr>

<tr class='failClass warning'>
    <td>WebService.test_data.cases.register.Register</td>
    <td class="text-center">9</td>
    <td class="text-center">5</td>
    <td class="text-center">4</td>
    <td class="text-center">0</td>
    <td class="text-center"><a href="javascript:showClassDetail('c2',9)" class="detail" id='c2'>详细</a></td>
</tr>

<tr id='ft2_1' class='none'>
    <td class='failCase'><div class='testcase'>test_register_1__1___sendmsg_____url__sms_service_war_1_0_ws_smsFacade_ws_wsdl____发送验证码______client_ip___192_168_1_225___tmpl_id__1__mobile____mobile_________sql___select_count__mobile___from_sms_db__num__t_mvcode_info__nu__where_Fmobile_no__mobile___n_______retCode__0__retInfo___ok______Method_not_found___SMSServiceImplService_SMSServiceImplPort_userRegister_____PASS__: list() -> new empty list</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_1'>失败</button>
    <div id='div_ft2_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_1'>失败</button>
    <div id='div_ft2_1' class="collapse in" align="left">
    <pre>
    
ft2_1: [2019-04-28 21:13:09,876]-[INFO]-[log_module.py-test_log]-[日志信息]:正在执行sendmsg模块1条用例，测试数据是{'client_ip':'192.168.1.225','tmpl_id':1,'mobile':'18296207778'}
[2019-04-28 21:13:09,935]-[INFO]-[log_module.py-test_log]-[日志信息]:实际结果是Method not found: 'SMSServiceImplService.SMSServiceImplPort.userRegister'，测试结果是：PASS
Traceback (most recent call last):
  File "D:\pycharm\WebService\test_data\cases\register.py", line 38, in test_register
    res=client.service.userRegister(eval(Params))
  File "C:\python35\lib\site-packages\suds\client.py", line 283, in __getattr__
    return getattr(port, name)
suds.MethodNotFound: Method not found: 'SMSServiceImplService.SMSServiceImplPort.userRegister'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\python35\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\pycharm\WebService\test_data\cases\register.py", line 67, in test_register
    self.assertEqual(ExpectedResult,str(res))
AssertionError: "{'retCode':0,'retInfo':'ok'}" != "Method not found: 'SMSServiceImplService.SMSServiceImplPort.userRegister'"
- {'retCode':0,'retInfo':'ok'}
+ Method not found: 'SMSServiceImplService.SMSServiceImplPort.userRegister'



    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_2' class='none'>
    <td class='failCase'><div class='testcase'>test_register_2__2___sendmsg_____url__sms_service_war_1_0_ws_smsFacade_ws_wsdl____手机号码不足11位______client_ip___192_168_1_225___tmpl_id__1__mobile___1369654123_____None___Server_raised_fault___手机号码错误____None__None_: list() -> new empty list</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_2'>失败</button>
    <div id='div_ft2_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_2'>失败</button>
    <div id='div_ft2_2' class="collapse in" align="left">
    <pre>
    
ft2_2: [2019-04-28 21:13:09,937]-[INFO]-[log_module.py-test_log]-[日志信息]:正在执行sendmsg模块2条用例，测试数据是{'client_ip':'192.168.1.225','tmpl_id':1,'mobile':'1369654123'}
[2019-04-28 21:13:10,019]-[INFO]-[log_module.py-test_log]-[日志信息]:实际结果是Method not found: 'SMSServiceImplService.SMSServiceImplPort.userRegister'，测试结果是：None
Traceback (most recent call last):
  File "D:\pycharm\WebService\test_data\cases\register.py", line 38, in test_register
    res=client.service.userRegister(eval(Params))
  File "C:\python35\lib\site-packages\suds\client.py", line 283, in __getattr__
    return getattr(port, name)
suds.MethodNotFound: Method not found: 'SMSServiceImplService.SMSServiceImplPort.userRegister'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\python35\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\pycharm\WebService\test_data\cases\register.py", line 67, in test_register
    self.assertEqual(ExpectedResult,str(res))
AssertionError: "Server raised fault: '手机号码错误'" != "Method not found: 'SMSServiceImplService.SMSServiceImplPort.userRegister'"
- Server raised fault: '手机号码错误'
+ Method not found: 'SMSServiceImplService.SMSServiceImplPort.userRegister'



    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_3' class='none'>
    <td class='failCase'><div class='testcase'>test_register_3__3___sendmsg_____url__sms_service_war_1_0_ws_smsFacade_ws_wsdl____手机号码大于11位______client_ip___192_168_1_225___tmpl_id__1__mobile___1369654123254_____None___Server_raised_fault___手机号码错误____None__None_: list() -> new empty list</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_3'>失败</button>
    <div id='div_ft2_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_3'>失败</button>
    <div id='div_ft2_3' class="collapse in" align="left">
    <pre>
    
ft2_3: [2019-04-28 21:13:10,021]-[INFO]-[log_module.py-test_log]-[日志信息]:正在执行sendmsg模块3条用例，测试数据是{'client_ip':'192.168.1.225','tmpl_id':1,'mobile':'1369654123254'}
[2019-04-28 21:13:10,080]-[INFO]-[log_module.py-test_log]-[日志信息]:实际结果是Method not found: 'SMSServiceImplService.SMSServiceImplPort.userRegister'，测试结果是：None
Traceback (most recent call last):
  File "D:\pycharm\WebService\test_data\cases\register.py", line 38, in test_register
    res=client.service.userRegister(eval(Params))
  File "C:\python35\lib\site-packages\suds\client.py", line 283, in __getattr__
    return getattr(port, name)
suds.MethodNotFound: Method not found: 'SMSServiceImplService.SMSServiceImplPort.userRegister'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\python35\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\pycharm\WebService\test_data\cases\register.py", line 67, in test_register
    self.assertEqual(ExpectedResult,str(res))
AssertionError: "Server raised fault: '手机号码错误'" != "Method not found: 'SMSServiceImplService.SMSServiceImplPort.userRegister'"
- Server raised fault: '手机号码错误'
+ Method not found: 'SMSServiceImplService.SMSServiceImplPort.userRegister'



    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_4' class='none'>
    <td class='failCase'><div class='testcase'>test_register_4__4___sendmsg_____url__sms_service_war_1_0_ws_smsFacade_ws_wsdl____不填手机号______client_ip___192_168_1_225___tmpl_id__1__mobile________None___Server_raised_fault___手机号码错误____None__None_: list() -> new empty list</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_4'>失败</button>
    <div id='div_ft2_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_4'>失败</button>
    <div id='div_ft2_4' class="collapse in" align="left">
    <pre>
    
ft2_4: [2019-04-28 21:13:10,082]-[INFO]-[log_module.py-test_log]-[日志信息]:正在执行sendmsg模块4条用例，测试数据是{'client_ip':'192.168.1.225','tmpl_id':1,'mobile':''}
[2019-04-28 21:13:10,145]-[INFO]-[log_module.py-test_log]-[日志信息]:实际结果是Method not found: 'SMSServiceImplService.SMSServiceImplPort.userRegister'，测试结果是：None
Traceback (most recent call last):
  File "D:\pycharm\WebService\test_data\cases\register.py", line 38, in test_register
    res=client.service.userRegister(eval(Params))
  File "C:\python35\lib\site-packages\suds\client.py", line 283, in __getattr__
    return getattr(port, name)
suds.MethodNotFound: Method not found: 'SMSServiceImplService.SMSServiceImplPort.userRegister'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\python35\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\pycharm\WebService\test_data\cases\register.py", line 67, in test_register
    self.assertEqual(ExpectedResult,str(res))
AssertionError: "Server raised fault: '手机号码错误'" != "Method not found: 'SMSServiceImplService.SMSServiceImplPort.userRegister'"
- Server raised fault: '手机号码错误'
+ Method not found: 'SMSServiceImplService.SMSServiceImplPort.userRegister'



    </pre>
    </div>
    </td>
</tr>

<tr id='pt2_5' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_register_5__5___register_____url__finance_user_info_war_1_0_ws_financeUserInfoFacade_ws_wsdl____正常注册______verify_code___fverifyCode___user_id____mobile____channel_id___1___pwd____pwd____mobile____mobile____ip___192_168_1_107________sq2___select_Fverify_code_from_sms_db__num__t_mvcode_info__nu__where_Fmobile_no__mobile____sq3___select_Fpwd_Fmobile_from_user_db_t_user_info_where_Fuser_id__mobile____sq4___select_count_Fuid__from_user_db_t_user_info_where_Fuser_id__mobile_________retCode__0__retInfo___ok______0____20042003____FAILED__: list() -> new empty list</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt2_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt2_5'>通过</button>
    <div id='div_pt2_5' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt2_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt2_5'>通过</button>
    <div id='div_pt2_5' class="collapse in" align="left">
    <pre>
    
pt2_5: [2019-04-28 21:13:10,342]-[INFO]-[log_module.py-test_log]-[日志信息]:正在执行register模块5条用例，测试数据是{'verify_code':'466568','user_id':'18296207778','channel_id':'1','pwd':'123456','mobile':'18296207778','ip':'192.168.1.107'}
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: 'xiaojian'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: 'oojian'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: 'fb7506'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '12950a'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: 'a9cd61'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '6b1e04'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: 'e2f059'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: 'ea5c13'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: 'little_kun'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: 'yoyocloud'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: 'a60be7'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '7b20ce'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '3b8765'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: 'df6095'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: 'bc728e'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: 'b0c4a6'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: 'e3960a'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '6f02c4'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '08419d'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '19e28b'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '2f5dce'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: 'd7a65f'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: 'k99018'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '郑倪别'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '褚葛摆'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '@#￥ABC'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '金葛掰'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '陶倪掰'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '秦任呗'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '吕唐别'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '华鲁玲'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '孙潘尚'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '陈薛呗'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '卫方玲'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '严柳郏'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '冯倪录'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '孔史尚'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '尤方农'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '施汤录'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '尤任国'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '何廉尚'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '朱鲍瞿'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '尤奚晏'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '王俞浦'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '魏昌充'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '魏汤瞿'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '钱贺立'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '韩花别'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '钱韦白'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '严马白'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '严潘别'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '韩倪败'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '华柳摆'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: 'luren'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '哈哈2'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '不行2'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '小明同学'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '5d2bf9'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: 'lurens'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '1627ad'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '123hgfgf56'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '728a5c'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: 'be4760'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '8a2c59'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: ' 西红柿'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: ''??????''")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: ''??BB7803''")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '0538db'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '0b9d5e'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '0dba3c'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '0f9145'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '12钻石增幅卷'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '13535544sss'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '145b02'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '160b72'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '1ed970'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '292b7b'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '2d8574'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '3985a7'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '3f9607'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '442c19'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '4a9083'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '4c6b3a'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '4d2013'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '5014ea'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '5241d0'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '5463af'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '58032c'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '5c3e8d'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '5c6b19'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '5fd96a'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '5fda72'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '5fea4c'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '670ca5'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '730b1e'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '7ae3b8'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '7ba534'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '7c9027'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '7fc98d'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '814e5b'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '832cb7'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '870eaf'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '8b2f1c'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '8cc87a'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '8d2407'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '90e837'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '9e803a'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '9ed081'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '?'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '??'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '??067A15'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '??123'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '???'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '?????'")
  result = self._query(query)
C:\python35\lib\site-packages\pymysql\cursors.py:170: Warning: (1292, "Truncated incorrect DOUBLE value: '??????'")
  result = self._query(query)
[2019-04-28 21:13:11,247]-[INFO]-[log_module.py-test_log]-[日志信息]:实际结果是(commResult){
   retCode = "0"
   retInfo = "ok"
 }，测试结果是：PASS


    </pre>
    </div>
    </td>
</tr>

<tr id='pt2_6' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_register_6__6___register_____url__finance_user_info_war_1_0_ws_financeUserInfoFacade_ws_wsdl____错误验证码______verify_code___00000___user_id____mobile____channel_id___1___pwd____pwd____mobile____mobile____ip___192_168_1_107_____None_____retCode__0__retInfo___ok_____None__None_: list() -> new empty list</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt2_6' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt2_6'>通过</button>
    <div id='div_pt2_6' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt2_6' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt2_6'>通过</button>
    <div id='div_pt2_6' class="collapse in" align="left">
    <pre>
    
pt2_6: [2019-04-28 21:13:11,248]-[INFO]-[log_module.py-test_log]-[日志信息]:正在执行register模块6条用例，测试数据是{'verify_code':'00000','user_id':'18296207778','channel_id':'1','pwd':'123456','mobile':'18296207778','ip':'192.168.1.107'}
[2019-04-28 21:13:11,462]-[INFO]-[log_module.py-test_log]-[日志信息]:实际结果是(commResult){
   retCode = "20042003"
   retInfo = "该用户已存在"
 }，测试结果是：PASS


    </pre>
    </div>
    </td>
</tr>

<tr id='pt2_7' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_register_7__7___register_____url__finance_user_info_war_1_0_ws_financeUserInfoFacade_ws_wsdl____重复注册______verify_code___fverifyCode___user_id____mobile____channel_id___1___pwd____pwd____mobile____mobile____ip___192_168_1_107_____None_____retCode__0__retInfo___ok_______commResult___n___retCode____20042003__n___retInfo____该用户已存在__n______PASS__: list() -> new empty list</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt2_7' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt2_7'>通过</button>
    <div id='div_pt2_7' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt2_7' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt2_7'>通过</button>
    <div id='div_pt2_7' class="collapse in" align="left">
    <pre>
    
pt2_7: [2019-04-28 21:13:11,462]-[INFO]-[log_module.py-test_log]-[日志信息]:正在执行register模块7条用例，测试数据是{'verify_code':'466568','user_id':'18296207778','channel_id':'1','pwd':'123456','mobile':'18296207778','ip':'192.168.1.107'}
[2019-04-28 21:13:11,690]-[INFO]-[log_module.py-test_log]-[日志信息]:实际结果是(commResult){
   retCode = "20042003"
   retInfo = "该用户已存在"
 }，测试结果是：PASS


    </pre>
    </div>
    </td>
</tr>

<tr id='pt2_8' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_register_8__8___register_____url__finance_user_info_war_1_0_ws_financeUserInfoFacade_ws_wsdl____手机号大于11位______verify_code___fverifyCode___user_id____mobile____channel_id___1___pwd___123456___mobile___1358634952468___ip___192_168_1_107_____None_____retCode__0__retInfo___ok_______commResult___n___retCode____19001__n___retInfo____手机号错误__n______PASS__: list() -> new empty list</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt2_8' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt2_8'>通过</button>
    <div id='div_pt2_8' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt2_8' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt2_8'>通过</button>
    <div id='div_pt2_8' class="collapse in" align="left">
    <pre>
    
pt2_8: [2019-04-28 21:13:11,690]-[INFO]-[log_module.py-test_log]-[日志信息]:正在执行register模块8条用例，测试数据是{'verify_code':'466568','user_id':'18296207778','channel_id':'1','pwd':'123456','mobile':'1358634952468','ip':'192.168.1.107'}
[2019-04-28 21:13:11,930]-[INFO]-[log_module.py-test_log]-[日志信息]:实际结果是(commResult){
   retCode = "19001"
   retInfo = "手机号错误"
 }，测试结果是：PASS


    </pre>
    </div>
    </td>
</tr>

<tr id='pt2_9' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_register_9__9___register_____url__finance_user_info_war_1_0_ws_financeUserInfoFacade_ws_wsdl____失效验证码______verify_code___865562___user_id___18296208167___channel_id___1___pwd___123456___mobile___18296208167___ip___192_168_1_107_____None_____retCode__0__retInfo___ok_____None__None_: list() -> new empty list</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt2_9' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt2_9'>通过</button>
    <div id='div_pt2_9' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt2_9' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt2_9'>通过</button>
    <div id='div_pt2_9' class="collapse in" align="left">
    <pre>
    
pt2_9: [2019-04-28 21:13:11,931]-[INFO]-[log_module.py-test_log]-[日志信息]:正在执行register模块9条用例，测试数据是{'verify_code':'865562','user_id':'18296208167','channel_id':'1','pwd':'123456','mobile':'18296208167','ip':'192.168.1.107'}
[2019-04-28 21:13:12,162]-[INFO]-[log_module.py-test_log]-[日志信息]:实际结果是(commResult){
   retCode = "30010010"
   retInfo = "验证码已过期"
 }，测试结果是：PASS


    </pre>
    </div>
    </td>
</tr>

<tr id='total_row' class="text-center active">
    <td>总计</td>
    <td>18</td>
    <td>9</td>
    <td>4</td>
    <td>5</td>
    <td>通过率：50.00%</td>
</tr>
</table>

<div id='ending'>&nbsp;</div>
    <div style=" position:fixed;right:50px; bottom:30px; width:20px; height:20px;cursor:pointer">
    <a href="#"><span class="glyphicon glyphicon-eject" style = "font-size:30px;" aria-hidden="true">
    </span></a></div>
    
</body>
</html>
